spring.application.name=backend-erp

# URL de conexión (formato: jdbc:postgresql://host:puerto/nombre_bd)
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_rrhh
spring.datasource.username=postgres
spring.datasource.password=RaggedSould
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Deshabilitar JMX para evitar conflictos de puerto en desarrollo
spring.jmx.enabled=false